version: '2'

services:

  jenkins:

    image: 'jenkins/jenkins:lts'

    environment:

      - JAVA_OPTS=-Djava.awt.headless=true -Dmail.smtp.starttls.enable=true

    labels:

      kompose.service.type: nodeport

    ports:

      - '8080:8080'

      - '50000:50000'

    volumes:

      - 'jenkins_home:/var/jenkins_home'

    networks:

      - bridge

  tomcat:

    image: 'tomcat:9.0.27-jdk8-openjdk'

    ports:

      - '80:8080'

    networks:

      - bridge

    volumes:

      - 'tomcat_conf:/usr/local/tomcat'

volumes:

  jenkins_home:

      external: true

  tomcat_conf:

      driver: local

networks: 

  bridge: